# Generated by Django 3.0.8 on 2020-07-21 23:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200721_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='EntryLevel',
            new_name='LogLevel',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.LogLevel'),
        ),
    ]
