# Generated by Django 3.0.8 on 2020-07-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200721_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
